version: '2'
services:
  postgres-container:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=coco
      - POSTGRES_USER=postgres-user
    ports:
      - '15432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
    driver: local
 
